#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export LIBDRM_DEBUG=0
xrandr --output DP-2 --off --output HDMI-0 --primary --auto
setxkbmap gb

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom --config ~/.config/picom/picom.conf &
dunst &
polybar &
