#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export LIBDRM_DEBUG=0

xrandr --output DP-2 --off --output HDMI-0 --primary --auto

setxkbmap gb

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom --config ~/.config/picom/picom.conf &
polybar &
